my_project/urls.py
from django.contrib import admin
from django.urls import path, re_path
from rappicrowd import views
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    # Handle both creations (POST) and listing (GET) of solicitantes
    re_path(r'^api/solicitantes/$', views.solicitantes_list),

    # Remove (DELETE) or update (PUT) the data of a single solicitante
    re_path(r'^api/solicitantes/(?P<pk>[0-9]+)$', views.solicitantes_detail),
]

rappicrowd/personins/urls.py
"""
Urls for Personins Web Api. This is needed for Django Framework
"""
from django.urls import path

from . import views

app_name = 'personins'
urlpatterns = [
    path('', views.index, name='index'),
    path('load/', views.load, name='load'),
]

rappicrowd/rappicrowd/urls.py
from django.contrib import admin
from django.urls import path, re_path, include # libraries for redirecting and include urls from others folders or apps
from django.conf.urls import url 
from rappicrowdContainer import views
from django.views.decorators.csrf import csrf_exempt # library to protect the view for attack cross site request forgery
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls), # url to administrative way django
    path('personins/', include('personins.urls')),  # url IBM Insights
    path(r'countries', views.CountriesAPIView.as_view(), name='countries-list'), # url rest api countries model
    path(r'states', views.StatesAPIView.as_view(), name='states-list'), # url rest api states model
    path(r'cities', views.CitiesAPIView.as_view(), name='cities-list'), # url rest api cities model
    path(r'educationLevels', views.EducationLevelsAPIView.as_view(), # url rest api educationLevels model
         name='educationlevels-list'),
    path(r'currencies', views.CurrenciesAPIView.as_view(), # url rest api currencies model
         name='currencies-list'),
    path(r'docutypes', views.DocutypesAPIView.as_view(), name='docutypes-list'), # url rest api docutypes model
    path(r'workers', views.WorkersAPIView.as_view(), name='workers-list'), # url rest api workers model
    path(r'investors', csrf_exempt(views.InvestorsAPIView.as_view()), # url rest api investors model
         name="investors-list"),
    path(r'investorsCreate', views.InvestorsCreateAPIView.as_view(), # url view creation investor
         name='investorscreate-list'),
    path(r'investorsPerWorkers', views.InvestorsPerWorkersAPIView.as_view(), # url rest api investors per workers model 
         name='investorsperworkers-list'),
    path(r'investorsPerWorkersTotalAmountPerWorker', views.InvestorsPerWorkersTotalAmountPerWorkerAPIView.as_view(), name='investorsperworkerstotalamountperworker-list'), # url rest api where only shows worker id and amount to calculate in the view with javascript the total amount per worker

    # update worker
    url(r'^workers/update/(?P<pk>[A-Za-z0-9]+)/$',
        views.WorkersUpdateView.as_view(), name='workers-update'), 
    # worker by primary key
    url(r'^workers/(?P<pk>[A-Za-z0-9]+)$',
        views.WorkerByDocument.as_view(), name='worker-by-document'),

    path('', include('frontend.urls')), # line to include the frontend urls from urls.py file for the frontend folder
    re_path('', views.index), 
    re_path(r'^$', views.index),
    re_path(r'^(?:.*)/?$', views.index),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # include the media files from media folder in the view

rappicrowd/personins/models.py
from django.db import models

# Create your models here.

rappicrowd/personins/views.py
"""
Views for Personins Web Api. This is needed for Django Framework
"""

from django.shortcuts import render
from django.http import HttpResponse
from personins import getpersonins
import json


def index(request):
    """
    Default url.
    Arguments:
        request: request object
    """

    return render(request, 'personins/index.html')


def load(request):
    """
    Url that send data to API
    Arguments:
        request: request object
    """

    profile = request.POST.get('profile')
    user_name = request.POST.get('user_name')
    mode = request.POST.get('mode')
    get_insights = getpersonins.get(user_name, profile, mode)

    return HttpResponse(get_insights, content_type='application/json')

rappicrowd/personins/templates/personins/index.html
<h1>Personal Insights of a Twetter Profile</h1>

<script>
function wait() {
	document.getElementById('status').style.display = 'block';
}
</script>
<form action="{% url 'personins:load' %}" method="post">{% csrf_token %}
 <b>Enter a public user profile begining with "@"</b></br>example: @elonmusk </br>
 <input type="text" name="user_name" id="user_name" value=""></br>
 <textarea id="profile" name="profile" rows="30" cols="100">
 </textarea></br>
 <input type="text" name="mode" id="mode" value="dev"></br>
 <input type="submit" value="Load" onclick="wait();">
</form>

<div id="status" style="text-align: center; color: blue; display: none;">
	<h3>Wait, this can take time...</h3>
</div>

rappicrowd/personins/templates/personins/load (old).html
<!DOCTYPE html>
<html>
  <head>
      <title>Personality Insights Results</title>
      <script src="https://cdn.anychart.com/releases/8.0.0/js/anychart-base.min.js"></script>
      <script>
        const result = {{ profile_result|safe }};
	    const personal = result.personality
        console.log(personal);
      </script>
  </head>
  <body>
	<h1>Results</h1>
    <div id="container0" style="width: 500px; height: 300px"></div>
	<div id="container1" style="width: 500px; height: 300px"></div>
	<div id="container2" style="width: 500px; height: 300px"></div>
	<div id="container3" style="width: 500px; height: 300px"></div>
	<div id="container4" style="width: 500px; height: 300px"></div>
	<script>

	for (let i = 0; i < personal.length; i++) {
		anychart.onDocumentReady(function() {

		let children = personal[i].children;
		let rows = [];
		for (let j = 0; j < children.length; j++) {
			let charScore = children[j].percentile * 100;
			let character = [children[j].name, charScore];
			rows.push(character);
		}

		// the data 
		let data = {
		  header: ["Name", "Score %"],
		  rows: rows};

		

		// create the chart
		let chart = anychart.bar();
	 
		// add the data
		chart.data(data);

		// set the chart title
		personScore = personal[i].percentile * 100 + "%";
		chart.title(personal[i].name + ", score: " + personScore);
		chart.container('container' + i);
		chart.draw();
	});
	}
	</script>
  </body>
</html>

rappicrowd/personins/templates/personins/load.html
<!DOCTYPE html>
<html>
  <head>
      <title>Personality Insights Results</title>
      <script>
        const result = {{ profile_result|safe }};
        console.log(result);
      </script>
  </head>
  <body>
	<h1>Results</h1>
 
  </body>
</html>